# 默认设置
default:
  groupCD:  500    # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 2000   # 群聊中个人操作冷却时间，单位毫秒

  onlyReplyAt: 0   # 是否只仅关注主动@机器人的消息， 0-否 1-是
  botAlias:        # 开启后则只回复@机器人的消息及特定前缀的消息，支持多个
    - 云崽
    - 云宝   
  
# 群单独设置，自动覆盖默认值
123456:
  groupCD:  500    # 群聊中所有指令操作冷却时间，单位毫秒,0则无限制
  singleCD: 2000   # 群聊中个人操作冷却时间，单位毫秒
