# 是否自动同意加好友 1-同意 0-不处理
autoFriend: 1
# 是否自动退群人数，当被好友拉进群时，群人数小于配置值自动退出， 默认50，0则不处理
autoQuit: 50
# 主人QQ号
masterQQ:


#白名单群，配置后只在该群生效
whiteGroup:

#黑名单群
blackGroup:
  - 213938015
#黑名单qq
blackQQ:
  - 528952540